FROM python:3.7.10-slim

WORKDIR /edutalk

# PREPARE STAGE
COPY ./edutalk-server/requirements.txt /tmp/requirements.txt

RUN apt update && \
    # Install build dependencies
    apt install -y --no-install-recommends curl && \
    curl -fsSL https://deb.nodesource.com/setup_lts.x | bash - && \
    apt install -y nodejs && \
    npm install -g yarn && \
    pip install --no-cache-dir -U pip && \
    pip install --no-cache-dir -r /tmp/requirements.txt && \
    # Remove build dependencies, unused packages and the packages index
    #
    # Ref: https://unix.stackexchange.com/questions/217369/clear-apt-get-list
    apt purge -y curl && \
    apt autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# BUILD STAGE
COPY ./edutalk-server /edutalk-server

RUN yarn --cwd /edutalk-server install --production=true && \
    # FIXME: `-e` is a workaround
    pip install --no-cache-dir -e /edutalk-server && \
    # generate default config
    edutalk genconf /edutalk/edutalk.ini
