# Generated by Django 3.2.5 on 2021-07-12 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFeatureObject',
            fields=[
                ('dfo_id', models.IntegerField(primary_key=True, serialize=False)),
                ('df_name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('sub', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.CharField(choices=[('NO', 'Normal'), ('GA', 'Gamma'), ('UN', 'Uniform')], default='NO', max_length=2)),
                ('mean', models.FloatField(default=0.5)),
                ('var', models.FloatField(default=0.25)),
                ('seed', models.IntegerField()),
                ('min', models.FloatField(default=0)),
                ('max', models.FloatField(default=1)),
                ('dfo_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_distribution', to='simtalk.devicefeatureobject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='simtalk.user')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=255)),
                ('sim', models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=3)),
                ('u_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='simtalk.user')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceObject',
            fields=[
                ('do_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dm_name', models.CharField(max_length=255)),
                ('sim', models.CharField(choices=[('on', 'on'), ('off', 'off')], default='off', max_length=3)),
                ('ccm_d_id', models.IntegerField(blank=True, default=None, null=True)),
                ('ag_token', models.CharField(blank=True, default='', max_length=36)),
                ('is_default', models.BooleanField(default=True)),
                ('p_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_objects', to='simtalk.project')),
            ],
        ),
        migrations.AddField(
            model_name='devicefeatureobject',
            name='do_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_feature_objects', to='simtalk.deviceobject'),
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('refresh_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='simtalk.refreshtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='simtalk.user')),
            ],
        ),
        migrations.CreateModel(
            name='ValueDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution', models.CharField(choices=[('NO', 'Normal'), ('GA', 'Gamma'), ('UN', 'Uniform')], default='NO', max_length=2)),
                ('mean', models.FloatField(default=0.5)),
                ('var', models.FloatField(default=0.25)),
                ('seed', models.IntegerField()),
                ('min', models.FloatField(default=0)),
                ('max', models.FloatField(default=1)),
                ('param_i', models.IntegerField()),
                ('param_type', models.CharField(choices=[('int', 'int'), ('float', 'float')], default='float', max_length=5)),
                ('dfo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_distributions', to='simtalk.devicefeatureobject')),
            ],
            options={
                'unique_together': {('dfo_id', 'param_i')},
            },
        ),
    ]
