"""add function.is_protect

Revision ID: 2017eaf51b5c
Revises: 9db8923bca1a
Create Date: 2021-04-20 11:36:46.627589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2017eaf51b5c'
down_revision = '9db8923bca1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'Function',
        sa.Column('is_protect', sa.Boolean(), server_default='0', nullable=False)
    )
    op.execute("UPDATE `Function` SET is_protect = false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Function', 'is_protect')
    # ### end Alembic commands ###
