"""init

Revision ID: 4363b14d282c
Revises:
Create Date: 2018-11-28 14:11:43.243261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4363b14d282c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'DeviceFeatureCategory',
        sa.Column('dfc_id', sa.Integer(), nullable=False),
        sa.Column('dfc_name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('dfc_id'),
        sa.UniqueConstraint('dfc_name'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'DeviceModel',
        sa.Column('dm_id', sa.Integer(), nullable=False),
        sa.Column('dm_name', sa.String(length=255), nullable=False),
        sa.Column('dm_type', sa.Enum('smartphone', 'wearable', 'other'), nullable=False),
        sa.PrimaryKeyConstraint('dm_id'),
        sa.UniqueConstraint('dm_name'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'Function',
        sa.Column('fn_id', sa.Integer(), nullable=False),
        sa.Column('fn_name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('fn_id'),
        sa.UniqueConstraint('fn_name'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'Tag',
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.Column('tag_name', sa.String(length=255), nullable=False),
        sa.Column('param_no', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('tag_id'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'Unit',
        sa.Column('unit_id', sa.Integer(), nullable=False),
        sa.Column('unit_name', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('unit_id'),
        sa.UniqueConstraint('unit_name'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'User',
        sa.Column('u_id', sa.Integer(), nullable=False),
        sa.Column('u_name', sa.String(length=255), nullable=False),
        sa.Column('passwd', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('u_id'),
        sa.UniqueConstraint('u_name'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'Version',
        sa.Column('version', sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint('version')
    )
    op.create_table(
        'Device',
        sa.Column('d_id', sa.Integer(), nullable=False),
        sa.Column('mac_addr', sa.String(length=255), nullable=False),
        sa.Column('monitor', sa.String(length=255), nullable=False),
        sa.Column('d_name', sa.String(length=255), nullable=False),
        sa.Column('status', sa.Enum('online', 'offline'), nullable=False),
        sa.Column('u_id', sa.Integer(), nullable=True),
        sa.Column('dm_id', sa.Integer(), nullable=False),
        sa.Column('is_sim', sa.Boolean(), nullable=False),
        sa.Column('register_time', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['dm_id'], ['DeviceModel.dm_id'], ),
        sa.ForeignKeyConstraint(['u_id'], ['User.u_id'], ),
        sa.PrimaryKeyConstraint('d_id'),
        sa.UniqueConstraint('mac_addr'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'DeviceFeature',
        sa.Column('df_id', sa.Integer(), nullable=False),
        sa.Column('df_name', sa.String(length=255), nullable=False),
        sa.Column('df_type', sa.Enum('input', 'output'), nullable=False),
        sa.Column('df_category', sa.String(length=255), nullable=False),
        sa.Column('param_no', sa.Integer(), nullable=False),
        sa.Column('comment', sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(['df_category'], ['DeviceFeatureCategory.dfc_name'], ),
        sa.PrimaryKeyConstraint('df_id'),
        sa.UniqueConstraint('df_name'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'FunctionVersion',
        sa.Column('fnvt_idx', sa.Integer(), nullable=False),
        sa.Column('fn_id', sa.Integer(), nullable=False),
        sa.Column('u_id', sa.Integer(), nullable=True),
        sa.Column('completeness', sa.Boolean(), nullable=True),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('code', sa.Text(), nullable=False),
        sa.Column('is_switch', sa.Boolean(), nullable=True),
        sa.Column('non_df_args', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['fn_id'], ['Function.fn_id'], ),
        sa.ForeignKeyConstraint(['u_id'], ['User.u_id'], ),
        sa.PrimaryKeyConstraint('fnvt_idx'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'Project',
        sa.Column('p_id', sa.Integer(), nullable=False),
        sa.Column('p_name', sa.String(length=255), nullable=False),
        sa.Column('u_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('on', 'off'), nullable=False),
        sa.Column('restart', sa.Boolean(), nullable=False),
        sa.Column('exception', sa.Text(), nullable=False),
        sa.Column('sim', sa.Enum('on', 'off'), nullable=False),
        sa.ForeignKeyConstraint(['u_id'], ['User.u_id'], ),
        sa.PrimaryKeyConstraint('p_id'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'Tag_Parameter',
        sa.Column('tagp_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=True),
        sa.Column('param_i', sa.Integer(), nullable=False),
        sa.Column('param_type',
                  sa.Enum('int', 'float', 'boolean', 'void', 'string', 'json'),
                  nullable=False),
        sa.Column('min', sa.Float(), nullable=True),
        sa.Column('max', sa.Float(), nullable=True),
        sa.Column('unit_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['tag_id'], ['Tag.tag_id'], ),
        sa.ForeignKeyConstraint(['unit_id'], ['Unit.unit_id'], ),
        sa.PrimaryKeyConstraint('tagp_id'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'DM_DF',
        sa.Column('mf_id', sa.Integer(), nullable=False),
        sa.Column('dm_id', sa.Integer(), nullable=False),
        sa.Column('df_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['df_id'], ['DeviceFeature.df_id'], ),
        sa.ForeignKeyConstraint(['dm_id'], ['DeviceModel.dm_id'], ),
        sa.PrimaryKeyConstraint('mf_id'),
        sa.UniqueConstraint('dm_id', 'df_id', name='dm_df'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'DeviceObject',
        sa.Column('do_id', sa.Integer(), nullable=False),
        sa.Column('dm_id', sa.Integer(), nullable=False),
        sa.Column('p_id', sa.Integer(), nullable=False),
        sa.Column('do_idx', sa.Integer(), nullable=False),
        sa.Column('d_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['d_id'], ['Device.d_id'], ),
        sa.ForeignKeyConstraint(['dm_id'], ['DeviceModel.dm_id'], ),
        sa.ForeignKeyConstraint(['p_id'], ['Project.p_id'], ),
        sa.PrimaryKeyConstraint('do_id'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'FunctionSDF',
        sa.Column('fnsdf_id', sa.Integer(), nullable=False),
        sa.Column('fn_id', sa.Integer(), nullable=False),
        sa.Column('u_id', sa.Integer(), nullable=True),
        sa.Column('df_id', sa.Integer(), nullable=True),
        sa.Column('display', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['df_id'], ['DeviceFeature.df_id'], ),
        sa.ForeignKeyConstraint(['fn_id'], ['Function.fn_id'], ),
        sa.ForeignKeyConstraint(['u_id'], ['User.u_id'], ),
        sa.PrimaryKeyConstraint('fnsdf_id'),
        sa.UniqueConstraint('fn_id', 'u_id', 'df_id', name='mf_tag'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'NetworkApplication',
        sa.Column('na_id', sa.Integer(), nullable=False),
        sa.Column('na_name', sa.String(length=255), nullable=False),
        sa.Column('na_idx', sa.Integer(), nullable=False),
        sa.Column('p_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['p_id'], ['Project.p_id'], ),
        sa.PrimaryKeyConstraint('na_id'),
        sa.UniqueConstraint('na_idx', 'p_id', name='na'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'DFObject',
        sa.Column('dfo_id', sa.Integer(), nullable=False),
        sa.Column('do_id', sa.Integer(), nullable=False),
        sa.Column('df_id', sa.Integer(), nullable=False),
        sa.Column('alias_name', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['df_id'], ['DeviceFeature.df_id'], ),
        sa.ForeignKeyConstraint(['do_id'], ['DeviceObject.do_id'], ),
        sa.PrimaryKeyConstraint('dfo_id'),
        sa.UniqueConstraint('do_id', 'df_id', name='dfo'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'DF_Parameter',
        sa.Column('dfp_id', sa.Integer(), nullable=False),
        sa.Column('df_id', sa.Integer(), nullable=True),
        sa.Column('mf_id', sa.Integer(), nullable=True),
        sa.Column('param_i', sa.Integer(), nullable=False),
        sa.Column('param_type',
                  sa.Enum('int', 'float', 'boolean', 'void', 'string', 'json'),
                  nullable=False),
        sa.Column('u_id', sa.Integer(), nullable=True),
        sa.Column('idf_type', sa.Enum('variant', 'sample'), nullable=False),
        sa.Column('fn_id', sa.Integer(), nullable=True),
        sa.Column('min', sa.Float(), nullable=False),
        sa.Column('max', sa.Float(), nullable=False),
        sa.Column('normalization', sa.Boolean(), nullable=False),
        sa.Column('unit_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['df_id'], ['DeviceFeature.df_id'], ),
        sa.ForeignKeyConstraint(['fn_id'], ['Function.fn_id'], ),
        sa.ForeignKeyConstraint(['mf_id'], ['DM_DF.mf_id'], ),
        sa.ForeignKeyConstraint(['u_id'], ['User.u_id'], ),
        sa.ForeignKeyConstraint(['unit_id'], ['Unit.unit_id'], ),
        sa.PrimaryKeyConstraint('dfp_id'),
        sa.UniqueConstraint('df_id', 'mf_id', 'param_i', 'u_id', name='df_parameter'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'DM_DF_Tag',
        sa.Column('mft_id', sa.Integer(), nullable=False),
        sa.Column('mf_id', sa.Integer(), nullable=False),
        sa.Column('tag_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['mf_id'], ['DM_DF.mf_id'], ),
        sa.ForeignKeyConstraint(['tag_id'], ['Tag.tag_id'], ),
        sa.PrimaryKeyConstraint('mft_id'),
        sa.UniqueConstraint('mf_id', 'tag_id', name='dm_df_tag'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'DF_Module',
        sa.Column('na_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('dfo_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('param_i', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('idf_type', sa.Enum('variant', 'sample'), nullable=False),
        sa.Column('fn_id', sa.Integer(), nullable=True),
        sa.Column('min', sa.Float(), nullable=False),
        sa.Column('max', sa.Float(), nullable=False),
        sa.Column('normalization', sa.Boolean(), nullable=False),
        sa.Column('color', sa.Enum('red', 'black'), nullable=False),
        sa.ForeignKeyConstraint(['dfo_id'], ['DFObject.dfo_id'], ),
        sa.ForeignKeyConstraint(['fn_id'], ['Function.fn_id'], ),
        sa.ForeignKeyConstraint(['na_id'], ['NetworkApplication.na_id'], ),
        sa.PrimaryKeyConstraint('na_id', 'dfo_id', 'param_i'),
        sqlite_autoincrement=True
    )
    op.create_table(
        'MultipleJoin_Module',
        sa.Column('na_id', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('param_i', sa.Integer(), autoincrement=False, nullable=False),
        sa.Column('fn_id', sa.Integer(), nullable=True),
        sa.Column('dfo_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['dfo_id'], ['DFObject.dfo_id'], ),
        sa.ForeignKeyConstraint(['fn_id'], ['Function.fn_id'], ),
        sa.ForeignKeyConstraint(['na_id'], ['NetworkApplication.na_id'], ),
        sa.PrimaryKeyConstraint('na_id', 'param_i'),
        sa.UniqueConstraint('na_id', 'dfo_id', name='mjm'),
        sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MultipleJoin_Module')
    op.drop_table('DF_Module')
    op.drop_table('DM_DF_Tag')
    op.drop_table('DF_Parameter')
    op.drop_table('DFObject')
    op.drop_table('NetworkApplication')
    op.drop_table('FunctionSDF')
    op.drop_table('DeviceObject')
    op.drop_table('DM_DF')
    op.drop_table('Tag_Parameter')
    op.drop_table('Project')
    op.drop_table('FunctionVersion')
    op.drop_table('DeviceFeature')
    op.drop_table('Device')
    op.drop_table('Version')
    op.drop_table('User')
    op.drop_table('Unit')
    op.drop_table('Tag')
    op.drop_table('Function')
    op.drop_table('DeviceModel')
    op.drop_table('DeviceFeatureCategory')
    # ### end Alembic commands ###
