"""device extra_url

Revision ID: b3236c44c0b0
Revises: cdaf47c1a0a8
Create Date: 2019-07-11 17:00:08.589991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3236c44c0b0'
down_revision = 'cdaf47c1a0a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Version')
    op.add_column(
        'Device',
        sa.Column('device_webpage',
                  sa.String(length=255),
                  server_default=sa.text("''"),
                  nullable=False))
    op.add_column(
        'Device',
        sa.Column('extra_setup_webpage',
                  sa.String(length=255),
                  server_default=sa.text("''"),
                  nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Device', 'extra_setup_webpage')
    op.drop_column('Device', 'device_webpage')
    op.create_table(
        'Version',
        sa.Column('version', sa.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint('version')
    )
    # ### end Alembic commands ###
